mybatis:  mapper-locations:  -   "classpath:/resources/com/minjoo/demo/mapper/*Mapper.xml"
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp  datasource:    hikari:      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: gkdwjdtkf1!
      driver-class-name: org.postgresql.Driver  h2:    console:      enabled: true
      
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false  

        
 
 
            